# Generated by Django 4.1.1 on 2022-10-03 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auth_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('stock', models.SmallIntegerField()),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firm.brand')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firm.category')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction', models.CharField(max_length=20)),
                ('quantity', models.SmallIntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('price_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('firm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firm.firm')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stproduct', to='firm.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.auth_user')),
            ],
        ),
    ]
