# Generated by Django 4.1.1 on 2022-10-03 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.category'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='firm',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='info.firm'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stproduct', to='info.product'),
        ),
    ]
